prefix = '.'
stop-words = 'lemur-stopwords.txt'

dataset = 'withoutbody-raw'
corpus = 'line.toml'
index = 'withoutbody-idx-raw'


[[analyzers]]
method = 'ngram-word'
ngram = 1
filter = 'default-unigram-chain'


[ranker]
method = "bm25"
k1 = 1.2
b = 0.75
k3 = 500